Add index
cse110-fa21-group24/cse110-fa21-group24 pull request #50
Opened 2021-11-10 20:27 UTC by grantDuntugan

Resolves #45 

**Description**

Added an empty index.html.

2021-11-10 20:50 UTC, minhdinh901 requested changes

2021-11-10 20:50 UTC, minhdinh901 commented on source/index.html
> +<body></body>
Add `html` tags and add the following metadata to `head`

```suggestion
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Impasta Rosta</title>
  </head>

  <body></body>
</html>
```

2021-11-10 20:52 UTC, minhdinh901 approved these changes

2021-11-11 19:54 UTC, keli214 approved these changes

2021-11-11 19:55 UTC, merged